apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sparksis
  description: The system operator
  annotations:
    github.com/project-slug: sparksis/sparksis
spec:
  profile:
    displayName: Colton English
    email: colton@sparksis.com
  memberOf: [admin]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
spec:
  type: team
  children: []
